# --appendonly yes：開啟 AOF 持久化
# --appendonly no：關閉 AOF（slave 從 master 同步即可）
# --appendfsync everysec：每秒同步 AOF

# version: '3' # 新版 Docker Compose v2 已忽略 version 欄位
services:
  master:
    image: redis:latest
    container_name: redis-master
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "128M"
    volumes:
      - './data/redis-master/data:/data' # 使用 bind mount 方式，windows 上可能因為權限問題無法 master-replica 同步成功
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST_PASSWORD=sa123456 # 設定 Redis AUTH 密碼
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD --dir /data --appendonly yes --appendfsync everysec" # 設定 Redis AUTH 密碼(使用 /bin/sh -c 才可以引用環境變數)
    networks:
      - master-slave_default

  slave1:
    image: redis:latest
    container_name: redis-slave1
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    volumes:
      - './data/redis-slave1/data:/data' # 使用 bind mount 方式，windows 上可能因為權限問題無法 master-replica 同步成功
    ports:
      - "6380:6379"
    environment:
      - REDIS_HOST_PASSWORD=sa123456
    command: /bin/sh -c "redis-server --replicaof redis-master 6379 --masterauth $$REDIS_HOST_PASSWORD --requirepass $$REDIS_HOST_PASSWORD --dir /data --appendonly no" # 設定 Redis AUTH Master 密碼(使用 /bin/sh -c 才可以引用環境變數)
    depends_on:
      - master
    networks:
      - master-slave_default

  slave2:
    image: redis:latest
    container_name: redis-slave2
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    volumes:
      - './data/redis-slave2/data:/data' # 使用 bind mount 方式，windows 上可能因為權限問題無法 master-replica 同步成功
    ports:
      - "6381:6379"
    environment:
      - REDIS_HOST_PASSWORD=sa123456
    command: /bin/sh -c "redis-server --replicaof redis-master 6379 --masterauth $$REDIS_HOST_PASSWORD --requirepass $$REDIS_HOST_PASSWORD --dir /data --appendonly no" # 設定 Redis AUTH Master 密碼(使用 /bin/sh -c 才可以引用環境變數)
    depends_on:
      - master
      - slave1
    networks:
      - master-slave_default

networks:
    master-slave_default:
        external: true