version: '3'
services:
    master:
        image: 'redis:latest'
        container_name: redis-master
        volumes:
            - './data/redis-master/data:/data'
        ports:
            - '6379:6379'
        environment:
            - REDIS_HOST_PASSWORD=sa123456
        command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD" # 設定 Redis AUTH 密碼(使用 /bin/sh -c 才可以引用環境變數)
        networks:
            - master-slave_default
    slave1:
        image: 'redis:latest'
        container_name: redis-slave1
        volumes:
            - './data/redis-slave1/data:/data'
        ports:
            - '6380:6379'
        environment:
            - REDIS_HOST_PASSWORD=sa123456
        command: /bin/sh -c "redis-server --slaveof redis-master 6379 --masterauth $$REDIS_HOST_PASSWORD" # 設定 Redis AUTH Master 密碼(使用 /bin/sh -c 才可以引用環境變數)
        depends_on:
            - master
        networks:
            - master-slave_default
    slave2:
        image: 'redis:latest'
        container_name: redis-slave2
        volumes:
            - './data/redis-slave2/data:/data'
        ports:
            - '6381:6379'
        environment:
            - REDIS_HOST_PASSWORD=sa123456
        command: /bin/sh -c "redis-server --slaveof redis-master 6379 --masterauth $$REDIS_HOST_PASSWORD" # 設定 Redis AUTH Master 密碼(使用 /bin/sh -c 才可以引用環境變數)
        depends_on:
            - master
            - slave1
        networks:
            - master-slave_default
networks: # 若後續要測試 sentinel，需與 sentinel 在同 docker 網路下
    master-slave_default:
        external: true