version: '3'
services: 
    sentinel1:
        container_name: redis-sentinel1
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: # 在 Dockerfile 中可使用 ARG 接收
            - REDIS_PORT=26379
            - REDIS_MASTER_IP=172.24.0.2 # 查詢 REDIS_MASTER 容器 IP 後置換: docker inspect redis-master | grep "IPAddress"
        volumes: 
            - ./data/redis-sentinel1/data:/data
        ports: 
        - 26379:26379
        networks: 
            - master-slave_default
    sentinel2:
        container_name: redis-sentinel2
        build:
            context: .
            dockerfile: ./Dockerfile
            args: # 在 Dockerfile 中可使用 ARG 接收
            - REDIS_PORT=26380
            - REDIS_MASTER_IP=172.24.0.2 # 查詢 REDIS_MASTER 容器 IP 後置換: docker inspect redis-master | grep "IPAddress"
        volumes: 
            - ./data/redis-sentinel2/data:/data
        ports: 
        - 26380:26379
        networks: 
            - master-slave_default
    sentinel3:
        container_name: redis-sentinel3
        build: 
            context: .
            dockerfile: ./Dockerfile
            args: # 在 Dockerfile 中可使用 ARG 接收
            - REDIS_PORT=26381
            - REDIS_MASTER_IP=172.24.0.2 # 查詢 REDIS_MASTER 容器 IP 後置換: docker inspect redis-master | grep "IPAddress"
        volumes: 
            - ./data/redis-sentinel3/data:/data
        ports: 
        - 26381:26379
        networks: 
            - master-slave_default
networks: # 若後續要測試 sentinel，需與 [主從模式 Redis] 在同 docker 網路下
    master-slave_default:
        external: true