version: '3'
services:
    sentinel1:
        container_name: redis-sentinel1
        build:
            context: .
            dockerfile: ./Dockerfile
            args: # 在 Dockerfile 中可使用 ARG 接收
                - REDIS_SENTINEL_PORT=${env_redis_sentinel_1_port}
                - REDIS_SENTINEL_PASSWORD=sa12345
                - REDIS_MASTER_NAME=mymaster # 從 sentinel 端，對被監控端的主從模式 REDIS 命名
                - REDIS_MASTER_IP=172.24.0.2 # 查詢要被監控的 REDIS_MASTER 容器 IP 後置換: docker inspect redis-master | grep "IPAddress"
                - REDIS_MASTER_PORT=6379
                - REDIS_MASTER_PASSWORD=sa123456
        volumes:
            - ./data/redis-sentinel1/data:/data
        ports:
            - 26379:${env_redis_sentinel_1_port}
        networks:
            - master-slave_default
    sentinel2:
        container_name: redis-sentinel2
        build:
            context: .
            dockerfile: ./Dockerfile
            args: # 在 Dockerfile 中可使用 ARG 接收
                - REDIS_SENTINEL_PORT=${env_redis_sentinel_2_port}
                - REDIS_SENTINEL_PASSWORD=sa12345
                - REDIS_MASTER_NAME=mymaster # 從 sentinel 端，對被監控端的主從模式 REDIS 命名
                - REDIS_MASTER_IP=172.24.0.2 # 查詢要被監控的 REDIS_MASTER 容器 IP 後置換: docker inspect redis-master | grep "IPAddress"
                - REDIS_MASTER_PORT=6379
                - REDIS_MASTER_PASSWORD=sa123456
        volumes:
            - ./data/redis-sentinel2/data:/data
        ports:
            - 26380:${env_redis_sentinel_2_port}
        networks:
            - master-slave_default
    sentinel3:
        container_name: redis-sentinel3
        build:
            context: .
            dockerfile: ./Dockerfile
            args: # 在 Dockerfile 中可使用 ARG 接收
                - REDIS_SENTINEL_PORT=${env_redis_sentinel_3_port}
                - REDIS_SENTINEL_PASSWORD=sa12345
                - REDIS_MASTER_NAME=mymaster # 從 sentinel 端，對被監控端的主從模式 REDIS 命名
                - REDIS_MASTER_IP=172.24.0.2 # 查詢要被監控的 REDIS_MASTER 容器 IP 後置換: docker inspect redis-master | grep "IPAddress"
                - REDIS_MASTER_PORT=6379
                - REDIS_MASTER_PASSWORD=sa123456
        volumes:
            - ./data/redis-sentinel3/data:/data
        ports:
            - 26381:${env_redis_sentinel_3_port}
        networks:
            - master-slave_default
networks: # 若後續要測試 sentinel，需與 [主從模式 Redis] 在同 docker 網路下
    master-slave_default:
        external: true
