version: '3'
services:
    redis1:
        image: redis:latest
        container_name: redis1
        ports:
            - '6379:6379'
        expose: # expose port to other containers
            - '6379'
            - '26379' # sentinel port
        volumes:
            - ./config/redis1.conf:/usr/local/etc/redis/redis.conf
            - ./config/sentinel.conf:/usr/local/etc/sentinel.conf
        # command: redis-server /usr/local/etc/redis/redis.conf
        command: >
          sh -c "
            apt -y update &&
            apt install -y telnet iputils-ping &&
            redis-server /usr/local/etc/redis/redis.conf &&
            redis-sentinel /usr/local/etc/sentinel.conf
          "
        networks:
            - redis-net
    redis2:
        image: redis:latest
        container_name: redis2
        ports:
            - '6380:6379'
        expose: # expose port to other containers
            - '6379'
            - '26379' # sentinel port
        volumes:
            - ./config/redis2.conf:/usr/local/etc/redis/redis.conf
            - ./config/sentinel.conf:/usr/local/etc/sentinel.conf
        # command: redis-server /usr/local/etc/redis/redis.conf
        command: >
          sh -c "
            apt -y update &&
            apt install -y telnet &&
            apt install -y iputils-ping &&
            redis-server /usr/local/etc/redis/redis.conf &&
            redis-sentinel /usr/local/etc/sentinel.conf
          "
        depends_on:
            - redis1
        networks:
            - redis-net
    redis3:
        image: redis:latest
        container_name: redis3
        ports:
            - '6381:6379'
        expose: # expose port to other containers
            - '6379'
            - '26379' # sentinel port
        volumes:
            - ./config/redis3.conf:/usr/local/etc/redis/redis.conf
            - ./config/sentinel.conf:/usr/local/etc/sentinel.conf
        # command: redis-server /usr/local/etc/redis/redis.conf
        command: >
          sh -c "
            apt -y update &&
            apt install -y telnet &&
            apt install -y iputils-ping &&
            redis-server /usr/local/etc/redis/redis.conf &&
            redis-sentinel /usr/local/etc/sentinel.conf
          "
        depends_on:
            - redis1
        networks:
            - redis-net

networks:
    redis-net:
        driver: bridge
